[helpers]
"concatenate" = ".dotter/helpers/concatenate.rhai"

[portage]

[portage.variables]
"march"          = "native"
"makeopts"       = 8
"python_targets" = [ ]
"llvm_targets"   = [ ]
"cpu_flags"      = [ ]
"video_cards"    = [ ]
"mirrors"        = [ ]

[portage.files."portage/make.conf"]
target = "/etc/portage/make.conf"
type   = "template"
owner  = "root"

[portage.files."portage/package.use/sys-apps/portage.use"]
target = "/etc/portage/package.use/sys-apps/portage.use"
type   = "template"
owner  = "root"

[rust]

[rust.variables]

[rust.files."portage/package.use/dev-lang/rust.use"]
target = "/etc/portage/package.use/dev-lang/rust.use"
type   = "template"
owner  = "root"
