[helpers]

[neovim.files]
"neovim/init.vim" = "~/.config/nvim/init.vim"

[neovim.variables]
tabwidth = 4
tabspace = true

[tmux.files]
"tmux/tmux.conf" = "~/.config/tmux/tmux.conf"

[zsh.files]
"zsh/zshrc"  = "~/.config/zsh/.zshrc"
"zsh/zpath"  = "~/.config/zsh/.zpath"
"zsh/zshenv" = "~/.config/zsh/.zshenv"
"zsh/zlogin" = "~/.config/zsh/.zlogin"
"zsh/zalias" = "~/.config/zsh/.zalias"
