[helpers]

[default.variables]
username = "rasmus"
locale   = "fi-FI"
history  = 2147483647

[nvim.files]
"nvim/init.vim" = "$XDG_CONFIG_HOME/nvim/init.vim"

[nvim.variables]
scrolloff = 5
tabwidth  = 4
tabspace  = true
textwidth = 80
folding   = "syntax"

[tmux]
depends = ["default"]

[tmux.files]
"tmux/tmux.conf" = "$XDG_CONFIG_HOME/tmux/tmux.conf"

[zsh]
depends = ["default"]

[zsh.files]
"zsh/zshrc"      = "$XDG_CONFIG_HOME/zsh/.zshrc"
"zsh/zpath"      = "$XDG_CONFIG_HOME/zsh/.zpath"
"zsh/zshenv"     = "$XDG_CONFIG_HOME/zsh/.zshenv"
"zsh/zlogin"     = "$XDG_CONFIG_HOME/zsh/.zlogin"
"zsh/zalias"     = "$XDG_CONFIG_HOME/zsh/.zalias"
"zsh/etc/zshenv" = { target = "/etc/zsh/zshenv", type = "symbolic", owner = "root"}

[task]
depends = ["default"]

[task.files]
"task/config" = "$XDG_CONFIG_HOME/task/config"
