[helpers]

[neovim.files]
"init.vim" = "~/.config/nvim/init.vim"

[neovim.variables]
tabwidth = 4
tabspace = true

[tmux.files]
"tmux.conf" = "~/.config/tmux/tmux.conf"

[zsh.files]
zshrc  = "~/.config/zsh/.zshrc"
zpath  = "~/.config/zsh/.zpath"
zshenv = "~/.config/zsh/.zshenv"
zlogin = "~/.config/zsh/.zlogin"
zalias = "~/.config/zsh/.zalias"
