[helpers]

[default.variables]
history = 2147483647

[nvim.files]
"nvim/init.vim" = "~/.config/nvim/init.vim"

[nvim.variables]
tabwidth  = 4
tabspace  = true
textwidth = 80

[tmux.files]
# requires "default"
"tmux/tmux.conf" = "~/.config/tmux/tmux.conf"

[zsh.files]
# requires "default"
"zsh/zshrc"  = "~/.config/zsh/.zshrc"
"zsh/zpath"  = "~/.config/zsh/.zpath"
"zsh/zshenv" = "~/.config/zsh/.zshenv"
"zsh/zlogin" = "~/.config/zsh/.zlogin"
"zsh/zalias" = "~/.config/zsh/.zalias"
