#!/usr/bin/env zsh

# XDG specification
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# PATH
export PATH="$PATH:$XDG_DATA_HOME/bin"
export PATH="$PATH:$XDG_DATA_HOME/cargo/bin"

# Editor
export EDITOR="nvim"
export VISUAL="nvim"
export PAGER="nvim -R"
export MANPAGER="nvim -c 'set ft=man' -"
export BAT_PAGER="less"

# History
export HISTFILE="$XDG_CACHE_HOME/zsh/history"
export HISTSIZE={{history}}
export SAVEHIST={{history}}

# Starship
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/config"

# Taskwarrior
export TASKRC="$XDG_CONFIG_HOME/task/config"
export TASKDATA="$XDG_DATA_HOME/task"

# Timewarrior
export TIMEWARRIORDB="$XDG_DATA_HOME/timew"

# Rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"

# GPG & Pass
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/pass"

export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority"
