#!/usr/bin/env zsh

source "$XDG_DATA_HOME/zsh/zpm/zpm.zsh" 2>/dev/null || {
    git clone https://github.com/zpm-zsh/zpm "$XDG_DATA_HOME/zsh/zpm"
    source "$XDG_DATA_HOME/zsh/zpm/zpm.zsh"
}

zpm load                                                                           \
    zpm-zsh/tmux,apply:path                                                        \
    zpm-zsh/ignored-users,async                                                    \
    zpm-zsh/check-deps,async                                                       \
    zpm-zsh/ls,async                                                               \
    zpm-zsh/colorize,async                                                         \
    zpm-zsh/ssh,async                                                              \
    voronkovich/gitignore.plugin.zsh,async                                         \
    mdumitru/fancy-ctrl-z,async                                                    \
    zsh-users/zsh-history-substring-search,source:zsh-history-substring-search.zsh \
    zdharma/fast-syntax-highlighting,async                                         \
    zsh-users/zsh-autosuggestions,source:zsh-autosuggestions.zsh,async             \

setopt hist_expire_dups_first hist_find_no_dups hist_ignore_dups bang_hist
setopt hist_ignore_space hist_reduce_blanks hist_verify inc_append_history
setopt append_history auto_remove_slash autocd braceccl chase_links nobeep
setopt interactive_comments multios nocaseglob nocheckjobs nohup numericglobsort
setopt combining_chars correct

unsetopt bg_nice clobber extended_history rm_star_silent

zstyle ':completion:*:processes' command 'NOCOLORS=1 ps -U $USER|sed "/ps/d"'
zstyle ':completion:*:processes' insert-ids menu yes select
zstyle ':completion:*:processes-names' command 'NOCOLORS=1 ps xho command|sed "s/://g"'
zstyle ':completion:*:processes' sort false

zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*:approximate:*' max-errors 'reply=($((($#PREFIX+$#SUFFIX)/3))numeric)'

zstyle '*' single-ignored show
zstyle ':completion:*:*:*:*:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'

zstyle ':completion:*:messages' format '%d'

zstyle ':completion:*:functions' ignored-patterns '_*'
zstyle ':completion:*:*:zcompile:*' ignored-patterns '(*~|*.zwc)'

zstyle ':completion:*:warnings' format "%{${c[red]}${c[bold]}%}No matches for:%{${c[yellow]}${c[bold]}%} %d"

if [[ "$CLICOLOR" != '0' ]]; then
  zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=36=31'
fi

zstyle ':completion:*' accept-exact '*(N)'
zstyle ':completion::complete:*' use-cache 1
zstyle ':completion::complete:*' cache-path "${TMPDIR:-/tmp}/zsh-${UID}"

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# zoxide
eval "$(zoxide init zsh)"

# Starship prompt
eval "$(starship init zsh)"
